---
- name: Generate and Install Configuration File
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "tmp"
    conf_file: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"

  tasks:
    - debug: var=tmp_dir

    - debug: var=conf_file


