---
- name: Install Configuration File
  hosts:
    - automation
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: install configuration file onto device
      juniper_junos_config:
        provider:
          host: "{{ ansible_host }}"
          user: "{{ username }}"
          passwd: "{{ password }}"
          timeout: 120
        load: merge
        src: "config/nameserver.conf"
